/* 
 * Copyright (c) 2018, Temple University
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * * Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 * * Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 * * All advertising materials features or use of this software must display 
 *   the following  acknowledgement
 *   This product includes software developed by Temple University
 * * Neither the name of the copyright holder nor the names of its 
 *   contributors may be used to endorse or promote products derived 
 *   from this software without specific prior written permission. 
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */
package edu.temple.cla.policydb.billshibernatedao;
// Generated Apr 23, 2010 11:18:57 AM by Hibernate Tools 3.2.1.GA

import java.util.Date;




/**
 * Bill generated by hbm2java
 */
public class Bill  implements java.io.Serializable {


     private String id;
     private Short chamber;
     private String session;
     private String bill;
     private String subtype;
     private String hyperlink;
     private String sponsor;
     private Short sponsorParty;
     private String sponsorCounty;
     private String sponsorTerms;
     private String abstract_;
     private Integer tax;
     private Integer eld;
     private Short conAmmend;
     private String actNo;
     private Date dateEnacted;
     private Short dayEnacted;
     private Short monthEnacted;
     private Short yearEnacted;
     private Integer code;
     private Integer commemorative;
     private Integer appropriations;
     private Integer $101p;
     private Integer $101o;
     private Integer $102p;
     private Integer $102o;
     private Integer $103p;
     private Integer $103o;
     private Integer $104p;
     private Integer $104o;
     private Integer $105p;
     private Integer $105o;
     private Integer $106p;
     private Integer $106o;
     private Integer $107p;
     private Integer $107o;
     private Integer $108p;
     private Integer $108o;
     private Integer $109p;
     private Integer $109o;
     private Integer $110p;
     private Integer $110o;
     private Integer $111p;
     private Integer $111o;
     private Integer $112p;
     private Integer $112o;
     private Integer $113p;
     private Integer $113o;
     private Integer $114p;
     private Integer $114o;
     private Integer $115p;
     private Integer $115o;
     private Integer $116p;
     private Integer $116o;
     private Integer $117p;
     private Integer $117o;
     private Integer $118p;
     private Integer $118o;
     private Integer $119p;
     private Integer $119o;
     private Integer $120p;
     private Integer $120o;
     private Integer $121p;
     private Integer $121o;
     private Integer $122p;
     private Integer $122o;
     private Integer $123p;
     private Integer $123o;
     private Integer $124p;
     private Integer $124o;
     private Integer $125p;
     private Integer $125o;
     private Integer $126p;
     private Integer $126o;
     private Integer $127p;
     private Integer $127o;
     private Integer $130p;
     private Integer $130o;
     private Integer $201p;
     private Integer $201o;
     private Integer $202p;
     private Integer $202o;
     private Integer $203p;
     private Integer $203o;
     private Integer $205p;
     private Integer $205o;
     private Integer $207p;
     private Integer $207o;
     private Integer $208p;
     private Integer $208o;
     private Integer $209p;
     private Integer $209o;
     private Integer $210p;
     private Integer $210o;
     private Integer $211p;
     private Integer $211o;
     private Integer $212p;
     private Integer $212o;
     private Integer $213p;
     private Integer $213o;
     private Integer $214p;
     private Integer $214o;
     private Integer $215p;
     private Integer $215o;
     private Integer $216p;
     private Integer $216o;
     private Integer $217p;
     private Integer $217o;
     private Integer $219p;
     private Integer $219o;
     private Integer $221p;
     private Integer $221o;
     private Integer $222p;
     private Integer $222o;
     private Integer $224p;
     private Integer $224o;
     private Integer $225p;
     private Integer $225o;
     private Integer $226p;
     private Integer $226o;
     private Integer $227p;
     private Integer $227o;
     private Integer $228p;
     private Integer $228o;
     private Integer $230p;
     private Integer $230o;
     private Integer $300;
     private Integer vetoIneligible;
     private Integer vetoed;
     private Integer lineItemVeto;
     private Integer vetoOverriden;
     private Integer lawNoGovSig;
     private Integer recalledByLeg;
     private Integer houseLastAction;
     private Integer senateLastAction;
     private Integer petition;
     private Date dateReferred;
     private Integer dayReferred;
     private Integer monthReferred;
     private Integer yearReferred;
     private Integer signedbyGov;

    public Bill() {
    }

	
    public Bill(String id) {
        this.id = id;
    }
    
    public Bill(String id, Short chamber, String session, String bill, String subtype, String hyperlink, String sponsor, Short sponsorParty, String sponsorCounty, String sponsorTerms, String abstract_, Integer tax, Integer eld, Short conAmmend, String actNo, Date dateEnacted, Short dayEnacted, Short monthEnacted, Short yearEnacted, Integer code, Integer commemorative, Integer appropriations, Integer $101p, Integer $101o, Integer $102p, Integer $102o, Integer $103p, Integer $103o, Integer $104p, Integer $104o, Integer $105p, Integer $105o, Integer $106p, Integer $106o, Integer $107p, Integer $107o, Integer $108p, Integer $108o, Integer $109p, Integer $109o, Integer $110p, Integer $110o, Integer $111p, Integer $111o, Integer $112p, Integer $112o, Integer $113p, Integer $113o, Integer $114p, Integer $114o, Integer $115p, Integer $115o, Integer $116p, Integer $116o, Integer $117p, Integer $117o, Integer $118p, Integer $118o, Integer $119p, Integer $119o, Integer $120p, Integer $120o, Integer $121p, Integer $121o, Integer $122p, Integer $122o, Integer $123p, Integer $123o, Integer $124p, Integer $124o, Integer $125p, Integer $125o, Integer $126p, Integer $126o, Integer $127p, Integer $127o, Integer $130p, Integer $130o, Integer $201p, Integer $201o, Integer $202p, Integer $202o, Integer $203p, Integer $203o, Integer $205p, Integer $205o, Integer $207p, Integer $207o, Integer $208p, Integer $208o, Integer $209p, Integer $209o, Integer $210p, Integer $210o, Integer $211p, Integer $211o, Integer $212p, Integer $212o, Integer $213p, Integer $213o, Integer $214p, Integer $214o, Integer $215p, Integer $215o, Integer $216p, Integer $216o, Integer $217p, Integer $217o, Integer $219p, Integer $219o, Integer $221p, Integer $221o, Integer $222p, Integer $222o, Integer $224p, Integer $224o, Integer $225p, Integer $225o, Integer $226p, Integer $226o, Integer $227p, Integer $227o, Integer $228p, Integer $228o, Integer $230p, Integer $230o, Integer $300, Integer vetoIneligible, Integer vetoed, Integer lineItemVeto, Integer vetoOverriden, Integer lawNoGovSig, Integer recalledByLeg, Integer houseLastAction, Integer senateLastAction, Integer petition, Date dateReferred, Integer dayReferred, Integer monthReferred, Integer yearReferred, Integer signedbyGov) {
       this.id = id;
       this.chamber = chamber;
       this.session = session;
       this.bill = bill;
       this.subtype = subtype;
       this.hyperlink = hyperlink;
       this.sponsor = sponsor;
       this.sponsorParty = sponsorParty;
       this.sponsorCounty = sponsorCounty;
       this.sponsorTerms = sponsorTerms;
       this.abstract_ = abstract_;
       this.tax = tax;
       this.eld = eld;
       this.conAmmend = conAmmend;
       this.actNo = actNo;
       this.dateEnacted = dateEnacted;
       this.dayEnacted = dayEnacted;
       this.monthEnacted = monthEnacted;
       this.yearEnacted = yearEnacted;
       this.code = code;
       this.commemorative = commemorative;
       this.appropriations = appropriations;
       this.$101p = $101p;
       this.$101o = $101o;
       this.$102p = $102p;
       this.$102o = $102o;
       this.$103p = $103p;
       this.$103o = $103o;
       this.$104p = $104p;
       this.$104o = $104o;
       this.$105p = $105p;
       this.$105o = $105o;
       this.$106p = $106p;
       this.$106o = $106o;
       this.$107p = $107p;
       this.$107o = $107o;
       this.$108p = $108p;
       this.$108o = $108o;
       this.$109p = $109p;
       this.$109o = $109o;
       this.$110p = $110p;
       this.$110o = $110o;
       this.$111p = $111p;
       this.$111o = $111o;
       this.$112p = $112p;
       this.$112o = $112o;
       this.$113p = $113p;
       this.$113o = $113o;
       this.$114p = $114p;
       this.$114o = $114o;
       this.$115p = $115p;
       this.$115o = $115o;
       this.$116p = $116p;
       this.$116o = $116o;
       this.$117p = $117p;
       this.$117o = $117o;
       this.$118p = $118p;
       this.$118o = $118o;
       this.$119p = $119p;
       this.$119o = $119o;
       this.$120p = $120p;
       this.$120o = $120o;
       this.$121p = $121p;
       this.$121o = $121o;
       this.$122p = $122p;
       this.$122o = $122o;
       this.$123p = $123p;
       this.$123o = $123o;
       this.$124p = $124p;
       this.$124o = $124o;
       this.$125p = $125p;
       this.$125o = $125o;
       this.$126p = $126p;
       this.$126o = $126o;
       this.$127p = $127p;
       this.$127o = $127o;
       this.$130p = $130p;
       this.$130o = $130o;
       this.$201p = $201p;
       this.$201o = $201o;
       this.$202p = $202p;
       this.$202o = $202o;
       this.$203p = $203p;
       this.$203o = $203o;
       this.$205p = $205p;
       this.$205o = $205o;
       this.$207p = $207p;
       this.$207o = $207o;
       this.$208p = $208p;
       this.$208o = $208o;
       this.$209p = $209p;
       this.$209o = $209o;
       this.$210p = $210p;
       this.$210o = $210o;
       this.$211p = $211p;
       this.$211o = $211o;
       this.$212p = $212p;
       this.$212o = $212o;
       this.$213p = $213p;
       this.$213o = $213o;
       this.$214p = $214p;
       this.$214o = $214o;
       this.$215p = $215p;
       this.$215o = $215o;
       this.$216p = $216p;
       this.$216o = $216o;
       this.$217p = $217p;
       this.$217o = $217o;
       this.$219p = $219p;
       this.$219o = $219o;
       this.$221p = $221p;
       this.$221o = $221o;
       this.$222p = $222p;
       this.$222o = $222o;
       this.$224p = $224p;
       this.$224o = $224o;
       this.$225p = $225p;
       this.$225o = $225o;
       this.$226p = $226p;
       this.$226o = $226o;
       this.$227p = $227p;
       this.$227o = $227o;
       this.$228p = $228p;
       this.$228o = $228o;
       this.$230p = $230p;
       this.$230o = $230o;
       this.$300 = $300;
       this.vetoIneligible = vetoIneligible;
       this.vetoed = vetoed;
       this.lineItemVeto = lineItemVeto;
       this.vetoOverriden = vetoOverriden;
       this.lawNoGovSig = lawNoGovSig;
       this.recalledByLeg = recalledByLeg;
       this.houseLastAction = houseLastAction;
       this.senateLastAction = senateLastAction;
       this.petition = petition;
       this.dateReferred = dateReferred;
       this.dayReferred = dayReferred;
       this.monthReferred = monthReferred;
       this.yearReferred = yearReferred;
       this.signedbyGov = signedbyGov;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public Short getChamber() {
        return this.chamber;
    }
    
    public void setChamber(Short chamber) {
        this.chamber = chamber;
    }

    public String getSession() {
        return this.session;
    }
    
    public void setSession(String session) {
        this.session = session;
    }
    public String getBill() {
        return this.bill;
    }
    
    public void setBill(String bill) {
        this.bill = bill;
    }
    
    public String getSubtype() {
        return this.subtype;
    }
    
    public void setSubtype(String subtype) {
        this.subtype = subtype;
    }
    
    public String getHyperlink() {
        return this.hyperlink;
    }
    
    public void setHyperlink(String hyperlink) {
        this.hyperlink = hyperlink;
    }
    public String getSponsor() {
        return this.sponsor;
    }
    
    public void setSponsor(String sponsor) {
        this.sponsor = sponsor;
    }
    public Short getSponsorParty() {
        return this.sponsorParty;
    }
    
    public void setSponsorParty(Short sponsorParty) {
        this.sponsorParty = sponsorParty;
    }
    public String getSponsorCounty() {
        return this.sponsorCounty;
    }
    
    public void setSponsorCounty(String sponsorCounty) {
        this.sponsorCounty = sponsorCounty;
    }
    public String getSponsorTerms() {
        return this.sponsorTerms;
    }
    
    public void setSponsorTerms(String sponsorTerms) {
        this.sponsorTerms = sponsorTerms;
    }
    public String getAbstract_() {
        return this.abstract_;
    }
    
    public void setAbstract_(String abstract_) {
        this.abstract_ = abstract_;
    }
    public Integer getTax() {
        return this.tax;
    }
    
    public void setTax(Integer tax) {
        this.tax = tax;
    }
    public Integer getEld() {
        return this.eld;
    }
    
    public void setEld(Integer eld) {
        this.eld = eld;
    }
    public Short getConAmmend() {
        return this.conAmmend;
    }
    
    public void setConAmmend(Short conAmmend) {
        this.conAmmend = conAmmend;
    }
    public String getActNo() {
        return this.actNo;
    }
    
    public void setActNo(String actNo) {
        this.actNo = actNo;
    }

    public Date getDateEnacted() {
        return this.dateEnacted;
    }

    public void setDateEnacted(Date dateEnacted) {
        this.dateEnacted = dateEnacted;
    }

    public Short getDayEnacted() {
        return this.dayEnacted;
    }

    public void setDayEnacted(Short dayEnacted) {
        this.dayEnacted = dayEnacted;
    }

    public Short getMonthEnacted() {
        return this.monthEnacted;
    }

    public void setMonthEnacted(Short monthEnacted) {
        this.monthEnacted = monthEnacted;
    }

    public Short getYearEnacted() {
        return this.yearEnacted;
    }
    
    public void setYearEnacted(Short yearEnacted) {
        this.yearEnacted = yearEnacted;
    }
    public Integer getCode() {
        return this.code;
    }
    
    public void setCode(Integer code) {
        this.code = code;
    }
    public Integer getCommemorative() {
        return this.commemorative;
    }
    
    public void setCommemorative(Integer commemorative) {
        this.commemorative = commemorative;
    }

    public Integer getAppropriations() {
        return this.appropriations;
    }
    
    public void setAppropriations(Integer appropriations){
        this.appropriations = appropriations;
    }
    
    public Integer getVetoIneligible() {
        return this.vetoIneligible;
    }
    
    public void setVetoIneligible(Integer vetoIneligible) {
        this.vetoIneligible = vetoIneligible;
    }
    public Integer getVetoed() {
        return this.vetoed;
    }
    
    public void setVetoed(Integer vetoed) {
        this.vetoed = vetoed;
    }
    public Integer getLineItemVeto() {
        return this.lineItemVeto;
    }
    
    public void setLineItemVeto(Integer lineItemVeto) {
        this.lineItemVeto = lineItemVeto;
    }
    public Integer getVetoOverriden() {
        return this.vetoOverriden;
    }
    
    public void setVetoOverriden(Integer vetoOverriden) {
        this.vetoOverriden = vetoOverriden;
    }
    public Integer getLawNoGovSig() {
        return this.lawNoGovSig;
    }
    
    public void setLawNoGovSig(Integer lawNoGovSig) {
        this.lawNoGovSig = lawNoGovSig;
    }
    public Integer getRecalledByLeg() {
        return this.recalledByLeg;
    }
    
    public void setRecalledByLeg(Integer recalledByLeg) {
        this.recalledByLeg = recalledByLeg;
    }
    public Integer getHouseLastAction() {
        return this.houseLastAction;
    }
    
    public void setHouseLastAction(Integer houseLastAction) {
        this.houseLastAction = houseLastAction;
    }
    public Integer getSenateLastAction() {
        return this.senateLastAction;
    }
    
    public void setSenateLastAction(Integer senateLastAction) {
        this.senateLastAction = senateLastAction;
    }

    public Integer getPetition() {
        return this.petition;
    }
    
    public void setPetition(Integer petition) {
        this.petition = petition;
    }

    public Date getDateReferred() {
        return this.dateReferred;
    }

    public void setDateReferred(Date dateReferred) {
        this.dateReferred = dateReferred;
    }

    public Integer getDayReferred() {
        return this.dayReferred;
    }
    
    public void setDayReferred(Integer dayReferred) {
        this.dayReferred = dayReferred;
    }
    public Integer getMonthReferred() {
        return this.monthReferred;
    }
    
    public void setMonthReferred(Integer monthReferred) {
        this.monthReferred = monthReferred;
    }
    public Integer getYearReferred() {
        return this.yearReferred;
    }
    
    public void setYearReferred(Integer yearReferred) {
        this.yearReferred = yearReferred;
    }
    public Integer getSignedbyGov() {
        return this.signedbyGov;
    }
    
    public void setSignedbyGov(Integer signedbyGov) {
        this.signedbyGov = signedbyGov;
    }

    /**
     * @return the $101p
     */
    public Integer get$101p() {
        return $101p;
    }

    /**
     * @param $101p the $101p to set
     */
    public void set$101p(Integer $101p) {
        this.$101p = $101p;
    }

    /**
     * @return the $101o
     */
    public Integer get$101o() {
        return $101o;
    }

    /**
     * @param $101o the $101o to set
     */
    public void set$101o(Integer $101o) {
        this.$101o = $101o;
    }

    /**
     * @return the $102p
     */
    public Integer get$102p() {
        return $102p;
    }

    /**
     * @param $102p the $102p to set
     */
    public void set$102p(Integer $102p) {
        this.$102p = $102p;
    }

    /**
     * @return the $102o
     */
    public Integer get$102o() {
        return $102o;
    }

    /**
     * @param $102o the $102o to set
     */
    public void set$102o(Integer $102o) {
        this.$102o = $102o;
    }

    /**
     * @return the $103p
     */
    public Integer get$103p() {
        return $103p;
    }

    /**
     * @param $103p the $103p to set
     */
    public void set$103p(Integer $103p) {
        this.$103p = $103p;
    }

    /**
     * @return the $103o
     */
    public Integer get$103o() {
        return $103o;
    }

    /**
     * @param $103o the $103o to set
     */
    public void set$103o(Integer $103o) {
        this.$103o = $103o;
    }

    /**
     * @return the $104p
     */
    public Integer get$104p() {
        return $104p;
    }

    /**
     * @param $104p the $104p to set
     */
    public void set$104p(Integer $104p) {
        this.$104p = $104p;
    }

    /**
     * @return the $104o
     */
    public Integer get$104o() {
        return $104o;
    }

    /**
     * @param $104o the $104o to set
     */
    public void set$104o(Integer $104o) {
        this.$104o = $104o;
    }

    /**
     * @return the $105p
     */
    public Integer get$105p() {
        return $105p;
    }

    /**
     * @param $105p the $105p to set
     */
    public void set$105p(Integer $105p) {
        this.$105p = $105p;
    }

    /**
     * @return the $105o
     */
    public Integer get$105o() {
        return $105o;
    }

    /**
     * @param $105o the $105o to set
     */
    public void set$105o(Integer $105o) {
        this.$105o = $105o;
    }

    /**
     * @return the $106p
     */
    public Integer get$106p() {
        return $106p;
    }

    /**
     * @param $106p the $106p to set
     */
    public void set$106p(Integer $106p) {
        this.$106p = $106p;
    }

    /**
     * @return the $106o
     */
    public Integer get$106o() {
        return $106o;
    }

    /**
     * @param $106o the $106o to set
     */
    public void set$106o(Integer $106o) {
        this.$106o = $106o;
    }

    /**
     * @return the $107p
     */
    public Integer get$107p() {
        return $107p;
    }

    /**
     * @param $107p the $107p to set
     */
    public void set$107p(Integer $107p) {
        this.$107p = $107p;
    }

    /**
     * @return the $107o
     */
    public Integer get$107o() {
        return $107o;
    }

    /**
     * @param $107o the $107o to set
     */
    public void set$107o(Integer $107o) {
        this.$107o = $107o;
    }

    /**
     * @return the $108p
     */
    public Integer get$108p() {
        return $108p;
    }

    /**
     * @param $108p the $108p to set
     */
    public void set$108p(Integer $108p) {
        this.$108p = $108p;
    }

    /**
     * @return the $108o
     */
    public Integer get$108o() {
        return $108o;
    }

    /**
     * @param $108o the $108o to set
     */
    public void set$108o(Integer $108o) {
        this.$108o = $108o;
    }

    /**
     * @return the $109p
     */
    public Integer get$109p() {
        return $109p;
    }

    /**
     * @param $109p the $109p to set
     */
    public void set$109p(Integer $109p) {
        this.$109p = $109p;
    }

    /**
     * @return the $109o
     */
    public Integer get$109o() {
        return $109o;
    }

    /**
     * @param $109o the $109o to set
     */
    public void set$109o(Integer $109o) {
        this.$109o = $109o;
    }

    /**
     * @return the $110p
     */
    public Integer get$110p() {
        return $110p;
    }

    /**
     * @param $110p the $110p to set
     */
    public void set$110p(Integer $110p) {
        this.$110p = $110p;
    }

    /**
     * @return the $110o
     */
    public Integer get$110o() {
        return $110o;
    }

    /**
     * @param $110o the $110o to set
     */
    public void set$110o(Integer $110o) {
        this.$110o = $110o;
    }

    /**
     * @return the $111p
     */
    public Integer get$111p() {
        return $111p;
    }

    /**
     * @param $111p the $111p to set
     */
    public void set$111p(Integer $111p) {
        this.$111p = $111p;
    }

    /**
     * @return the $111o
     */
    public Integer get$111o() {
        return $111o;
    }

    /**
     * @param $111o the $111o to set
     */
    public void set$111o(Integer $111o) {
        this.$111o = $111o;
    }

    /**
     * @return the $112p
     */
    public Integer get$112p() {
        return $112p;
    }

    /**
     * @param $112p the $112p to set
     */
    public void set$112p(Integer $112p) {
        this.$112p = $112p;
    }

    /**
     * @return the $112o
     */
    public Integer get$112o() {
        return $112o;
    }

    /**
     * @param $112o the $112o to set
     */
    public void set$112o(Integer $112o) {
        this.$112o = $112o;
    }

    /**
     * @return the $113p
     */
    public Integer get$113p() {
        return $113p;
    }

    /**
     * @param $113p the $113p to set
     */
    public void set$113p(Integer $113p) {
        this.$113p = $113p;
    }

    /**
     * @return the $113o
     */
    public Integer get$113o() {
        return $113o;
    }

    /**
     * @param $113o the $113o to set
     */
    public void set$113o(Integer $113o) {
        this.$113o = $113o;
    }

    /**
     * @return the $114p
     */
    public Integer get$114p() {
        return $114p;
    }

    /**
     * @param $114p the $114p to set
     */
    public void set$114p(Integer $114p) {
        this.$114p = $114p;
    }

    /**
     * @return the $114o
     */
    public Integer get$114o() {
        return $114o;
    }

    /**
     * @param $114o the $114o to set
     */
    public void set$114o(Integer $114o) {
        this.$114o = $114o;
    }

    /**
     * @return the $115p
     */
    public Integer get$115p() {
        return $115p;
    }

    /**
     * @param $115p the $115p to set
     */
    public void set$115p(Integer $115p) {
        this.$115p = $115p;
    }

    /**
     * @return the $115o
     */
    public Integer get$115o() {
        return $115o;
    }

    /**
     * @param $115o the $115o to set
     */
    public void set$115o(Integer $115o) {
        this.$115o = $115o;
    }

    /**
     * @return the $116p
     */
    public Integer get$116p() {
        return $116p;
    }

    /**
     * @param $116p the $116p to set
     */
    public void set$116p(Integer $116p) {
        this.$116p = $116p;
    }

    /**
     * @return the $116o
     */
    public Integer get$116o() {
        return $116o;
    }

    /**
     * @param $116o the $116o to set
     */
    public void set$116o(Integer $116o) {
        this.$116o = $116o;
    }

    /**
     * @return the $117p
     */
    public Integer get$117p() {
        return $117p;
    }

    /**
     * @param $117p the $117p to set
     */
    public void set$117p(Integer $117p) {
        this.$117p = $117p;
    }

    /**
     * @return the $117o
     */
    public Integer get$117o() {
        return $117o;
    }

    /**
     * @param $117o the $117o to set
     */
    public void set$117o(Integer $117o) {
        this.$117o = $117o;
    }

    /**
     * @return the $118p
     */
    public Integer get$118p() {
        return $118p;
    }

    /**
     * @param $118p the $118p to set
     */
    public void set$118p(Integer $118p) {
        this.$118p = $118p;
    }

    /**
     * @return the $118o
     */
    public Integer get$118o() {
        return $118o;
    }

    /**
     * @param $118o the $118o to set
     */
    public void set$118o(Integer $118o) {
        this.$118o = $118o;
    }

    /**
     * @return the $119p
     */
    public Integer get$119p() {
        return $119p;
    }

    /**
     * @param $119p the $119p to set
     */
    public void set$119p(Integer $119p) {
        this.$119p = $119p;
    }

    /**
     * @return the $119o
     */
    public Integer get$119o() {
        return $119o;
    }

    /**
     * @param $119o the $119o to set
     */
    public void set$119o(Integer $119o) {
        this.$119o = $119o;
    }

    /**
     * @return the $120p
     */
    public Integer get$120p() {
        return $120p;
    }

    /**
     * @param $120p the $120p to set
     */
    public void set$120p(Integer $120p) {
        this.$120p = $120p;
    }

    /**
     * @return the $120o
     */
    public Integer get$120o() {
        return $120o;
    }

    /**
     * @param $120o the $120o to set
     */
    public void set$120o(Integer $120o) {
        this.$120o = $120o;
    }

    /**
     * @return the $121p
     */
    public Integer get$121p() {
        return $121p;
    }

    /**
     * @param $121p the $121p to set
     */
    public void set$121p(Integer $121p) {
        this.$121p = $121p;
    }

    /**
     * @return the $121o
     */
    public Integer get$121o() {
        return $121o;
    }

    /**
     * @param $121o the $121o to set
     */
    public void set$121o(Integer $121o) {
        this.$121o = $121o;
    }

    /**
     * @return the $122p
     */
    public Integer get$122p() {
        return $122p;
    }

    /**
     * @param $122p the $122p to set
     */
    public void set$122p(Integer $122p) {
        this.$122p = $122p;
    }

    /**
     * @return the $122o
     */
    public Integer get$122o() {
        return $122o;
    }

    /**
     * @param $122o the $122o to set
     */
    public void set$122o(Integer $122o) {
        this.$122o = $122o;
    }

    /**
     * @return the $123p
     */
    public Integer get$123p() {
        return $123p;
    }

    /**
     * @param $123p the $123p to set
     */
    public void set$123p(Integer $123p) {
        this.$123p = $123p;
    }

    /**
     * @return the $123o
     */
    public Integer get$123o() {
        return $123o;
    }

    /**
     * @param $123o the $123o to set
     */
    public void set$123o(Integer $123o) {
        this.$123o = $123o;
    }

    /**
     * @return the $124p
     */
    public Integer get$124p() {
        return $124p;
    }

    /**
     * @param $124p the $124p to set
     */
    public void set$124p(Integer $124p) {
        this.$124p = $124p;
    }

    /**
     * @return the $124o
     */
    public Integer get$124o() {
        return $124o;
    }

    /**
     * @param $124o the $124o to set
     */
    public void set$124o(Integer $124o) {
        this.$124o = $124o;
    }

    /**
     * @return the $125p
     */
    public Integer get$125p() {
        return $125p;
    }

    /**
     * @param $125p the $125p to set
     */
    public void set$125p(Integer $125p) {
        this.$125p = $125p;
    }

    /**
     * @return the $125o
     */
    public Integer get$125o() {
        return $125o;
    }

    /**
     * @param $125o the $125o to set
     */
    public void set$125o(Integer $125o) {
        this.$125o = $125o;
    }

    /**
     * @return the $126p
     */
    public Integer get$126p() {
        return $126p;
    }

    /**
     * @param $126p the $126p to set
     */
    public void set$126p(Integer $126p) {
        this.$126p = $126p;
    }

    /**
     * @return the $126o
     */
    public Integer get$126o() {
        return $126o;
    }

    /**
     * @param $126o the $126o to set
     */
    public void set$126o(Integer $126o) {
        this.$126o = $126o;
    }

    /**
     * @return the $201p
     */
    public Integer get$201p() {
        return $201p;
    }

    /**
     * @param $201p the $201p to set
     */
    public void set$201p(Integer $201p) {
        this.$201p = $201p;
    }

    /**
     * @return the $201o
     */
    public Integer get$201o() {
        return $201o;
    }

    /**
     * @param $201o the $201o to set
     */
    public void set$201o(Integer $201o) {
        this.$201o = $201o;
    }

    /**
     * @return the $202p
     */
    public Integer get$202p() {
        return $202p;
    }

    /**
     * @param $202p the $202p to set
     */
    public void set$202p(Integer $202p) {
        this.$202p = $202p;
    }

    /**
     * @return the $202o
     */
    public Integer get$202o() {
        return $202o;
    }

    /**
     * @param $202o the $202o to set
     */
    public void set$202o(Integer $202o) {
        this.$202o = $202o;
    }

    /**
     * @return the $203p
     */
    public Integer get$203p() {
        return $203p;
    }

    /**
     * @param $203p the $203p to set
     */
    public void set$203p(Integer $203p) {
        this.$203p = $203p;
    }

    /**
     * @return the $203o
     */
    public Integer get$203o() {
        return $203o;
    }

    /**
     * @param $203o the $203o to set
     */
    public void set$203o(Integer $203o) {
        this.$203o = $203o;
    }

    /**
     * @return the $205p
     */
    public Integer get$205p() {
        return $205p;
    }

    /**
     * @param $205p the $205p to set
     */
    public void set$205p(Integer $205p) {
        this.$205p = $205p;
    }

    /**
     * @return the $205o
     */
    public Integer get$205o() {
        return $205o;
    }

    /**
     * @param $205o the $205o to set
     */
    public void set$205o(Integer $205o) {
        this.$205o = $205o;
    }

    /**
     * @return the $207p
     */
    public Integer get$207p() {
        return $207p;
    }

    /**
     * @param $207p the $207p to set
     */
    public void set$207p(Integer $207p) {
        this.$207p = $207p;
    }

    /**
     * @return the $207o
     */
    public Integer get$207o() {
        return $207o;
    }

    /**
     * @param $207o the $207o to set
     */
    public void set$207o(Integer $207o) {
        this.$207o = $207o;
    }

    /**
     * @return the $208p
     */
    public Integer get$208p() {
        return $208p;
    }

    /**
     * @param $208p the $208p to set
     */
    public void set$208p(Integer $208p) {
        this.$208p = $208p;
    }

    /**
     * @return the $208o
     */
    public Integer get$208o() {
        return $208o;
    }

    /**
     * @param $208o the $208o to set
     */
    public void set$208o(Integer $208o) {
        this.$208o = $208o;
    }

    /**
     * @return the $209p
     */
    public Integer get$209p() {
        return $209p;
    }

    /**
     * @param $209p the $209p to set
     */
    public void set$209p(Integer $209p) {
        this.$209p = $209p;
    }

    /**
     * @return the $209o
     */
    public Integer get$209o() {
        return $209o;
    }

    /**
     * @param $209o the $209o to set
     */
    public void set$209o(Integer $209o) {
        this.$209o = $209o;
    }

    /**
     * @return the $210p
     */
    public Integer get$210p() {
        return $210p;
    }

    /**
     * @param $210p the $210p to set
     */
    public void set$210p(Integer $210p) {
        this.$210p = $210p;
    }

    /**
     * @return the $210o
     */
    public Integer get$210o() {
        return $210o;
    }

    /**
     * @param $210o the $210o to set
     */
    public void set$210o(Integer $210o) {
        this.$210o = $210o;
    }

    /**
     * @return the $211p
     */
    public Integer get$211p() {
        return $211p;
    }

    /**
     * @param $211p the $211p to set
     */
    public void set$211p(Integer $211p) {
        this.$211p = $211p;
    }

    /**
     * @return the $211o
     */
    public Integer get$211o() {
        return $211o;
    }

    /**
     * @param $211o the $211o to set
     */
    public void set$211o(Integer $211o) {
        this.$211o = $211o;
    }

    /**
     * @return the $212p
     */
    public Integer get$212p() {
        return $212p;
    }

    /**
     * @param $212p the $212p to set
     */
    public void set$212p(Integer $212p) {
        this.$212p = $212p;
    }

    /**
     * @return the $212o
     */
    public Integer get$212o() {
        return $212o;
    }

    /**
     * @param $212o the $212o to set
     */
    public void set$212o(Integer $212o) {
        this.$212o = $212o;
    }

    /**
     * @return the $213p
     */
    public Integer get$213p() {
        return $213p;
    }

    /**
     * @param $213p the $213p to set
     */
    public void set$213p(Integer $213p) {
        this.$213p = $213p;
    }

    /**
     * @return the $213o
     */
    public Integer get$213o() {
        return $213o;
    }

    /**
     * @param $213o the $213o to set
     */
    public void set$213o(Integer $213o) {
        this.$213o = $213o;
    }

    /**
     * @return the $214p
     */
    public Integer get$214p() {
        return $214p;
    }

    /**
     * @param $214p the $214p to set
     */
    public void set$214p(Integer $214p) {
        this.$214p = $214p;
    }

    /**
     * @return the $214o
     */
    public Integer get$214o() {
        return $214o;
    }

    /**
     * @param $214o the $214o to set
     */
    public void set$214o(Integer $214o) {
        this.$214o = $214o;
    }

    /**
     * @return the $215p
     */
    public Integer get$215p() {
        return $215p;
    }

    /**
     * @param $215p the $215p to set
     */
    public void set$215p(Integer $215p) {
        this.$215p = $215p;
    }

    /**
     * @return the $215o
     */
    public Integer get$215o() {
        return $215o;
    }

    /**
     * @param $215o the $215o to set
     */
    public void set$215o(Integer $215o) {
        this.$215o = $215o;
    }

    /**
     * @return the $216p
     */
    public Integer get$216p() {
        return $216p;
    }

    /**
     * @param $216p the $216p to set
     */
    public void set$216p(Integer $216p) {
        this.$216p = $216p;
    }

    /**
     * @return the $216o
     */
    public Integer get$216o() {
        return $216o;
    }

    /**
     * @param $216o the $216o to set
     */
    public void set$216o(Integer $216o) {
        this.$216o = $216o;
    }

    /**
     * @return the $217p
     */
    public Integer get$217p() {
        return $217p;
    }

    /**
     * @param $217p the $217p to set
     */
    public void set$217p(Integer $217p) {
        this.$217p = $217p;
    }

    /**
     * @return the $217o
     */
    public Integer get$217o() {
        return $217o;
    }

    /**
     * @param $217o the $217o to set
     */
    public void set$217o(Integer $217o) {
        this.$217o = $217o;
    }

    /**
     * @return the $219p
     */
    public Integer get$219p() {
        return $219p;
    }

    /**
     * @param $219p the $219p to set
     */
    public void set$219p(Integer $219p) {
        this.$219p = $219p;
    }

    /**
     * @return the $219o
     */
    public Integer get$219o() {
        return $219o;
    }

    /**
     * @param $219o the $219o to set
     */
    public void set$219o(Integer $219o) {
        this.$219o = $219o;
    }

    /**
     * @return the $221p
     */
    public Integer get$221p() {
        return $221p;
    }

    /**
     * @param $221p the $221p to set
     */
    public void set$221p(Integer $221p) {
        this.$221p = $221p;
    }

    /**
     * @return the $221o
     */
    public Integer get$221o() {
        return $221o;
    }

    /**
     * @param $221o the $221o to set
     */
    public void set$221o(Integer $221o) {
        this.$221o = $221o;
    }

    /**
     * @return the $222p
     */
    public Integer get$222p() {
        return $222p;
    }

    /**
     * @param $222p the $222p to set
     */
    public void set$222p(Integer $222p) {
        this.$222p = $222p;
    }

    /**
     * @return the $222o
     */
    public Integer get$222o() {
        return $222o;
    }

    /**
     * @param $222o the $222o to set
     */
    public void set$222o(Integer $222o) {
        this.$222o = $222o;
    }

    /**
     * @return the $224p
     */
    public Integer get$224p() {
        return $224p;
    }

    /**
     * @param $224p the $224p to set
     */
    public void set$224p(Integer $224p) {
        this.$224p = $224p;
    }

    /**
     * @return the $224o
     */
    public Integer get$224o() {
        return $224o;
    }

    /**
     * @param $224o the $224o to set
     */
    public void set$224o(Integer $224o) {
        this.$224o = $224o;
    }

    /**
     * @return the $225p
     */
    public Integer get$225p() {
        return $225p;
    }

    /**
     * @param $225p the $225p to set
     */
    public void set$225p(Integer $225p) {
        this.$225p = $225p;
    }

    /**
     * @return the $225o
     */
    public Integer get$225o() {
        return $225o;
    }

    /**
     * @param $225o the $225o to set
     */
    public void set$225o(Integer $225o) {
        this.$225o = $225o;
    }

    /**
     * @return the $226p
     */
    public Integer get$226p() {
        return $226p;
    }

    /**
     * @param $226p the $226p to set
     */
    public void set$226p(Integer $226p) {
        this.$226p = $226p;
    }

    /**
     * @return the $226o
     */
    public Integer get$226o() {
        return $226o;
    }

    /**
     * @param $226o the $226o to set
     */
    public void set$226o(Integer $226o) {
        this.$226o = $226o;
    }

    /**
     * @return the $227p
     */
    public Integer get$227p() {
        return $227p;
    }

    /**
     * @param $227p the $227p to set
     */
    public void set$227p(Integer $227p) {
        this.$227p = $227p;
    }

    /**
     * @return the $227o
     */
    public Integer get$227o() {
        return $227o;
    }

    /**
     * @param $227o the $227o to set
     */
    public void set$227o(Integer $227o) {
        this.$227o = $227o;
    }

    /**
     * @return the $228p
     */
    public Integer get$228p() {
        return $228p;
    }

    /**
     * @param $228p the $228p to set
     */
    public void set$228p(Integer $228p) {
        this.$228p = $228p;
    }

    /**
     * @return the $228o
     */
    public Integer get$228o() {
        return $228o;
    }

    /**
     * @param $228o the $228o to set
     */
    public void set$228o(Integer $228o) {
        this.$228o = $228o;
    }

    /**
     * @return the $230p
     */
    public Integer get$230p() {
        return $230p;
    }

    /**
     * @param $230p the $230p to set
     */
    public void set$230p(Integer $230p) {
        this.$230p = $230p;
    }

    /**
     * @return the $230o
     */
    public Integer get$230o() {
        return $230o;
    }

    /**
     * @param $230o the $230o to set
     */
    public void set$230o(Integer $230o) {
        this.$230o = $230o;
    }

    /**
     * @return the $300
     */
    public Integer get$300() {
        return $300;
    }

    /**
     * @param $300 the $300 to set
     */
    public void set$300(Integer $300) {
        this.$300 = $300;
    }

    /**
     * @return the $127p
     */
    public Integer get$127p() {
        return $127p;
    }

    /**
     * @param $127p the $127p to set
     */
    public void set$127p(Integer $127p) {
        this.$127p = $127p;
    }

    /**
     * @return the $127o
     */
    public Integer get$127o() {
        return $127o;
    }

    /**
     * @param $127o the $127o to set
     */
    public void set$127o(Integer $127o) {
        this.$127o = $127o;
    }

    /**
     * @return the $130p
     */
    public Integer get$130p() {
        return $130p;
    }

    /**
     * @param $130p the $130p to set
     */
    public void set$130p(Integer $130p) {
        this.$130p = $130p;
    }

    /**
     * @return the $130o
     */
    public Integer get$130o() {
        return $130o;
    }

    /**
     * @param $130o the $130o to set
     */
    public void set$130o(Integer $130o) {
        this.$130o = $130o;
    }
    
}


